#!/bin/sh
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`anakata\`;
CREATE DATABASE IF NOT EXISTS \`anakata_test\`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON \`anakata\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`anakata_test\`.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
